spring:
  logging:
    level:
      org.springframework: DEBUG
  server:
    error:
    include-message: always
    include-binding-errors: always
  datasource:
    url: jdbc:mysql://localhost:3306/multirestaurants?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true